### PR TITLE
fix: "Enum not found"

### PR DESCRIPTION
**Pull request by NorDroN**

### CODE REVIEW

**Comment by ssut** [comment]
I just have published v1.1.0 on npm with this pr. thank you.

**Comment by NorDroN** [comment]
Thanks a lot!

**Comment by NorDroN** [comment]
Houston, we have a problem...
I noticed that v1.1.0 doesn't have any changes :(

**Comment by ssut** [comment]
I'm sorry I will take a look.

**Comment by ssut** [comment]
I republished the package with version v1.1.1.

**Comment by NorDroN** [comment]
It's ok now.

**Pull request merged**
